#!/bin/bash
#
# License: CC0
#
# To the extent possible under law, the person who associated CC0 with
# this project has waived all copyright and related or neighboring rights
# to this project.
# 
# You should have received a copy of the CC0 legalcode along with this
# work.  If not, see <http://creativecommons.org/publicdomain/zero/1.0/>.
#

export D=32
export M=500

if [[ "$1" != "" ]] ; then
  export D="$1"
fi

gcc -O3 randpoly.c -o randpoly
./randpoly $D $M | xargs -n1 -I{} mpsolve -p '{}' | tr -d '(),' > rp-d$D.gp
cat rp-d$D.gp | ./clog.py > ln_rp-d$D.gp
